name: How to survive as a human giraffe
favicon: null
layout_spectrum: 0.8424134757369757
typography_spectrum: 0.4296523407101631
title: 'Dr. Tall, or, How to stop worrying and survive as a human giraffe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#439cce'
    - '#010000'
    - '#fefced'
    - '#fba64f'
    - '#6e3102'
  brandStrength: 0.4375
  lightness: 0.14820694969967008
  saturation: 0.6332981195300817
  rhythmicContrast: 0.7768060807138681
purpose: []
